/**
 * Idempotent seeder for Node project (Postgres + Sequelize).
 * Mirrors the Laravel seeders but uses the updated User schema:
 *  - id: string (cuid, generated by User model hook)
 *  - role: enum('owner','staff','client')
 *  - status: enum('active','invited','disabled')
 *  - avatarUrl, lastLoginAt, mfa_enabled, createdAt, updatedAt
 *
 * Usage:
 *  const { runSeeders } = require('./seeders/runSeeders');
 *  await runSeeders();
 */

const { Role, Permission, PlanSubscription, User, sequelize } = require('../models');

async function seedRolePermissions() {
  const permissionsData = [
    // users
    { name: 'users.view', description: 'View users', module: 'users' },
    { name: 'users.create', description: 'Create users', module: 'users' },
    { name: 'users.edit', description: 'Edit users', module: 'users' },
    { name: 'users.delete', description: 'Delete users', module: 'users' },

    // roles
    { name: 'roles.view', description: 'View roles', module: 'roles' },
    { name: 'roles.create', description: 'Create roles', module: 'roles' },
    { name: 'roles.edit', description: 'Edit roles', module: 'roles' },
    { name: 'roles.delete', description: 'Delete roles', module: 'roles' },

    // permissions
    { name: 'permissions.view', description: 'View permissions', module: 'permissions' },
    { name: 'permissions.create', description: 'Create permissions', module: 'permissions' },
    { name: 'permissions.edit', description: 'Edit permissions', module: 'permissions' },
    { name: 'permissions.delete', description: 'Delete permissions', module: 'permissions' },

    // plans
    { name: 'plans.view', description: 'View plans', module: 'plans' },
    { name: 'plans.create', description: 'Create plans', module: 'plans' },
    { name: 'plans.edit', description: 'Edit plans', module: 'plans' },
    { name: 'plans.delete', description: 'Delete plans', module: 'plans' },
  ];

  const createdPermissions = [];
  for (const p of permissionsData) {
    const [perm] = await Permission.findOrCreate({
      where: { name: p.name },
      defaults: { description: p.description, module: p.module, is_active: true },
    });
    createdPermissions.push(perm);
  }

  const [adminRole] = await Role.findOrCreate({
    where: { name: 'admin' },
    defaults: { description: 'Administrator with full access', is_active: true },
  });

  const [clientRole] = await Role.findOrCreate({
    where: { name: 'client' },
    defaults: { description: 'Regular client user', is_active: true },
  });

  const [moderatorRole] = await Role.findOrCreate({
    where: { name: 'moderator' },
    defaults: { description: 'Moderator with limited admin access', is_active: true },
  });

  // Give admin all permissions
  const allPerms = await Permission.findAll();
  await adminRole.setPermissions(allPerms.map(p => p.id));

  // Give moderator a subset
  const moderatorPermissionNames = ['users.view', 'users.edit', 'plans.view'];
  const moderatorPerms = await Permission.findAll({ where: { name: moderatorPermissionNames } });
  await moderatorRole.setPermissions(moderatorPerms.map(p => p.id));

  return {
    createdPermissions: createdPermissions.map(p => p.name),
    rolesCreated: ['admin', 'client', 'moderator'],
  };
}

async function seedPlanSubscriptions() {
  const plans = [
    {
      name: 'DreamStarter',
      type: 'Standard',
      monthly_price: 99.0,
      annual_price: 960.0,
      description: 'For freelancers, side-hustlers, service providers & new businesses',
      features: [
        '4-page branded website (Home, About, Services/Contact)',
        'FREE SSL Certificate – Secure HTTPS site',
        'Mobile-ready + SEO-friendly',
        'Hosting + 2 Business Emails',
        'Monthly edits, updates & tech support',
        '8 Custom Social Media Posts (Facebook & Instagram)',
        'Scheduled content with your branding',
        'WhatsApp/Contact Form Setup',
        'Google Business Profile Assistance',
      ],
      additionalinfo: ['Delivered in 5–7 days', 'Minimum 3-Month Contract', 'Or Pay Annually & Save 20% (£960/year instead of £1,200)'],
      billing_period: 'month',
      is_active: true,
      popular: false,
    },
    {
      name: 'DreamStore',
      type: 'Pro',
      monthly_price: 179.0,
      annual_price: 1716.0,
      description: 'Everything in DreamStarter, PLUS',
      features: [
        'E-Commerce Website with Shop, Cart & Checkout',
        'Secure SSL for Payments',
        'Up to 30 Product Uploads',
        'Stripe / PayPal Integration',
        'Order & Shipping Management',
        'Abandoned Cart Recovery',
        'Invoice & Confirmation Email Setup',
        '10 Social Media Posts/Month + 1 Product Promo Graphic',
      ],
      additionalinfo: ['Delivered in 5–7 days', 'Minimum 3-Month Contract', 'Or Pay Annually & Save 20% (£1,716/year instead of £2,148)'],
      billing_period: 'month',
      is_active: true,
      popular: true,
    },
    {
      name: 'Enterprise',
      type: 'Business',
      monthly_price: 249.0,
      annual_price: 2390.0,
      description: 'Enterprise plan for large organizations',
      features: [
        'Up to 10 Custom Pages (Services, Blog, Portfolio, FAQs, Reviews, etc.)',
        'WhatsApp Chat or Booking Integration',
        'CRM & Email Automation Setup',
        'GDPR Compliant + Cookie & Privacy Policy',
        'Brand Strategy & UX Customisation',
        'Google Analytics + Monthly Insights',
        '12–16 Social Media Posts/Month + Stories/Reels Suggestions',
        'Custom Graphics, Content Ideas, and Personal Support',
      ],
      additionalinfo: ['Minimum 3-Month Contract', 'Or Pay Annually & Save 20% (£2,390/year instead of £2,988)'],
      billing_period: 'month',
      is_active: true,
      popular: false,
    },
  ];

  const created = [];
  for (const p of plans) {
    const [plan] = await PlanSubscription.findOrCreate({
      where: { name: p.name },
      defaults: {
        type: p.type,
        monthly_price: p.monthly_price,
        annual_price: p.annual_price,
        description: p.description,
        features: p.features,
        additionalinfo: p.additionalinfo,
        billing_period: p.billing_period,
        is_active: p.is_active,
        popular: p.popular,
      },
    });
    created.push(plan.name);
  }

  return { plansCreated: created };
}

async function seedUsers() {
  const results = [];

  // Admin user -> set role field to 'owner' (enum owner|staff|client)
  const [adminUser, adminCreated] = await User.findOrCreate({
    where: { email: 'admin@admin.com' },
    defaults: {
      name: 'Admin User',
      phone: '9999999999',
      password: 'password', // will be hashed in model hook
      role: 'owner',
      status: 'active',
      avatarUrl: null,
      mfa_enabled: true, // Enforce MFA for owner so login works with MFA enabled
    },
  });

  // Attach pivot admin role
  const adminRole = await Role.findOne({ where: { name: 'admin' } });
  if (adminRole) {
    const has = await adminUser.hasRole ? await adminUser.hasRole('admin') : (await adminUser.getRoles()).map(r => r.name).includes('admin');
    if (!has) await adminUser.addRole(adminRole);
  }
  results.push({ email: adminUser.email, created: adminCreated });

  // Manager / moderator -> staff role
  const [managerUser, managerCreated] = await User.findOrCreate({
    where: { email: 'manager@manager.com' },
    defaults: {
      name: 'Manager User',
      phone: '8888888888',
      password: 'password',
      role: 'staff',
      status: 'active',
      avatarUrl: null,
      mfa_enabled: true, // staff must have MFA enabled
    },
  });

  const moderatorRole = await Role.findOne({ where: { name: 'moderator' } });
  if (moderatorRole) {
    const has = await managerUser.hasRole ? await managerUser.hasRole('moderator') : (await managerUser.getRoles()).map(r => r.name).includes('moderator');
    if (!has) await managerUser.addRole(moderatorRole);
  }
  results.push({ email: managerUser.email, created: managerCreated });

  // Clients
  const clientRole = await Role.findOne({ where: { name: 'client' } });

  const [client1, c1created] = await User.findOrCreate({
    where: { email: 'client1@client.com' },
    defaults: {
      name: 'Client User 1',
      phone: '7777777777',
      password: 'password',
      role: 'client',
      status: 'active',
      avatarUrl: null,
      mfa_enabled: false,
    },
  });
  if (clientRole) {
    const has = await client1.hasRole ? await client1.hasRole('client') : (await client1.getRoles()).map(r => r.name).includes('client');
    if (!has) await client1.addRole(clientRole);
  }
  results.push({ email: client1.email, created: c1created });

  const [client2, c2created] = await User.findOrCreate({
    where: { email: 'client2@client.com' },
    defaults: {
      name: 'Client User 2',
      phone: '6666666666',
      password: 'password',
      role: 'client',
      status: 'active',
      avatarUrl: null,
      mfa_enabled: false,
    },
  });
  if (clientRole) {
    const has = await client2.hasRole ? await client2.hasRole('client') : (await client2.getRoles()).map(r => r.name).includes('client');
    if (!has) await client2.addRole(clientRole);
  }
  results.push({ email: client2.email, created: c2created });

  return results;
}

async function runSeeders({ transaction } = {}) {
  // Use a transaction if provided to keep operations atomic if desired.
  const t = transaction || null;
  // Wrap the three main seeder functions
  const rp = await seedRolePermissions();
  const plans = await seedPlanSubscriptions();
  const users = await seedUsers();

  return { rolePermissions: rp, plans, users };
}

module.exports = { runSeeders };